<?php
$sLangName  = "English";
$iLangNr    = 1;
$aLang = array(
    'jxfiles_menu'            => 'File Administration',
    'JXFILES_TITLE'           => 'File Administration',
    'JXFILES_FILENAME'        => 'Name',
    'JXFILES_FILETYPE'        => 'Type',
    'JXFILES_FILERIGHTS'      => 'Rights',
    'JXFILES_FILESIZE'        => 'Size',
    'JXFILES_FILEDATE'        => 'Date',
    'JXFILES_FILEACTION'      => 'Action',
    'JXFILES_IMAGEFILE'       => ' Image',
    'JXFILES_DOCUMENTFILE'    => ' Document',
    'JXFILES_FILE'            => ' File',
    'JXFILES_DIRECTORY'       => 'Folder',
    'JXFILES_ERRORONUPLOAD'   => 'Error on uploading the file:',
    'JXFILES_UPLOADERROR1'    => 'The uploaded file exceeds the upload_max_filesize directive in php.ini.',
    'JXFILES_UPLOADERROR2'    => 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form.',
    'JXFILES_UPLOADERROR3'    => 'The uploaded file was only partially uploaded.',
    'JXFILES_UPLOADERROR4'    => 'No file was uploaded.',
    'JXFILES_UPLOADERROR6'    => 'Missing a temporary folder.',
    'JXFILES_UPLOADERROR7'    => 'Failed to write file to disk.',
    'JXFILES_UPLOADERROR8'    => 'A PHP extension stopped the file upload. PHP does not provide a way to ascertain which extension caused the file upload to stop; examining the list of loaded extensions with phpinfo() may help.',
    'JXFILES_UPLOADSUCCESS1'  => 'File',
    'JXFILES_UPLOADSUCCESS2'  => 'successfully uploaded',
    'JXFILES_RENAME_TITLE'    => 'Rename file',
    'JXFILES_DELETE_TITLE'    => 'Delete file',
    'JXFILES_DELETE_QUESTION' => 'This file %s will be deleted!<br /><br />Do want to to do this really?',
    'JXFILES_RENAME_OLDFILE'  => 'Filename',
    'JXFILES_RENAME_NEWFILE'  => 'New filename',
    'JXFILES_RENAME_BUTTON'   => 'Rename',
    'JXFILES_DELETE_BUTTON'   => 'Delete',
    'JXFILES_CANCEL_BUTTON'   => 'Cancel',
    
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES1'   => 'Directory 1',
    'SHOP_MODULE_sJxFilesDir1Path'             => 'Path',
    'SHOP_MODULE_sJxFilesDir1Title'            => 'Title',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES2'   => 'Directory 2',
    'SHOP_MODULE_sJxFilesDir2Path'             => 'Path',
    'SHOP_MODULE_sJxFilesDir2Title'            => 'Title',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES3'   => 'Directory 3',
    'SHOP_MODULE_sJxFilesDir3Path'             => 'Path',
    'SHOP_MODULE_sJxFilesDir3Title'            => 'Title',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES4'   => 'Directory 4',
    'SHOP_MODULE_sJxFilesDir4Path'             => 'Path',
    'SHOP_MODULE_sJxFilesDir4Title'            => 'Title',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES5'   => 'Directory 5',
    'SHOP_MODULE_sJxFilesDir5Path'             => 'Path',
    'SHOP_MODULE_sJxFilesDir5Title'            => 'Title',
    
    'charset'                 => 'ISO-8859-15',
);

?>