<?php
$sLangName  = "Deutsch";
$iLangNr    = 0;
$aLang = array(
    'jxfiles_menu'            => 'Datei-Verwaltung',
    'JXFILES_TITLE'           => 'Datei-Verwaltung',
    'JXFILES_FILENAME'        => 'Name',
    'JXFILES_FILETYPE'        => 'Typ',
    'JXFILES_FILERIGHTS'      => 'Rechte',
    'JXFILES_FILESIZE'        => 'Gr&ouml;&szlig;e',
    'JXFILES_FILEDATE'        => 'Datum',
    'JXFILES_FILEACTION'      => 'Aktion',
    'JXFILES_IMAGEFILE'       => '-Bilddatei',
    'JXFILES_DOCUMENTFILE'    => '-Dokument',
    'JXFILES_FILE'            => '-Datei',
    'JXFILES_DIRECTORY'       => 'Ordner',
    'JXFILES_ERRORONUPLOAD'   => 'Fehler beim Hochladen der Datei:',
    'JXFILES_UPLOADERROR1'    => 'Die hochgeladene Datei &uuml;berschreitet die in der Anweisung <br>upload_max_filesize in php.ini festgelegte Gr&ouml;&szlig;e.',
    'JXFILES_UPLOADERROR2'    => 'Die hochgeladene Datei &uuml;berschreitet die in dem HTML Formular <br>mittels der Anweisung MAX_FILE_SIZE angegebene maximale Dateigr&ouml;&szlig;e.',
    'JXFILES_UPLOADERROR3'    => 'Die Datei wurde nur teilweise hochgeladen.',
    'JXFILES_UPLOADERROR4'    => 'Es wurde keine Datei hochgeladen.',
    'JXFILES_UPLOADERROR6'    => 'Fehlender tempor&auml;rer Ordner.',
    'JXFILES_UPLOADERROR7'    => 'Speichern der Datei auf die Festplatte ist fehlgeschlagen.',
    'JXFILES_UPLOADERROR8'    => 'Eine PHP Erweiterung hat den Upload der Datei gestoppt. PHP bietet keine M&ouml;glichkeit an,<br> um festzustellen welche Erweiterung das Hochladen der Datei gestoppt hat. <br>&Uuml;berprüfung aller geladenen Erweiterungen mittels phpinfo() k&ouml;nnte helfen.',
    'JXFILES_UPLOADSUCCESS1'  => 'Datei',
    'JXFILES_UPLOADSUCCESS2'  => 'erfolgreich hochgeladen',
    'JXFILES_RENAME_TITLE'    => 'Datei umbenennen',
    'JXFILES_DELETE_TITLE'    => 'Datei l&ouml;schen',
    'JXFILES_RENAME_OLDFILE'  => 'Dateiname',
    'JXFILES_RENAME_NEWFILE'  => 'Neuer Dateiname',
    'JXFILES_RENAME_BUTTON'   => 'Umbenennen',
    'JXFILES_DELETE_BUTTON'   => 'L&ouml;schen',
    'JXFILES_CANCEL_BUTTON'   => 'Abbrechen',
    
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES1'   => 'Verzeichnis 1',
    'SHOP_MODULE_sJxFilesDir1Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir1Title'            => 'Titel',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES2'   => 'Verzeichnis 2',
    'SHOP_MODULE_sJxFilesDir2Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir2Title'            => 'Titel',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES3'   => 'Verzeichnis 3',
    'SHOP_MODULE_sJxFilesDir3Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir3Title'            => 'Titel',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES4'   => 'Verzeichnis 4',
    'SHOP_MODULE_sJxFilesDir4Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir4Title'            => 'Titel',
    'SHOP_MODULE_GROUP_JXFILES_DIRECTORIES5'   => 'Verzeichnis 5',
    'SHOP_MODULE_sJxFilesDir5Path'             => 'Pfad',
    'SHOP_MODULE_sJxFilesDir5Title'            => 'Titel',
    
    'charset'                 => 'ISO-8859-15',
);

?>